# Generated by Django 5.2.8 on 2025-11-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Movie',
        ),
    ]
