# Generated by Django 5.2.8 on 2025-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_director_genre_movie_director_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='films.genre'),
        ),
    ]
